site_name: Ellar
site_description: Ellar - Python ASGI web framework for building fast, efficient and scalable RESTAPIs and server-side application.
site_url: https://github.com/eadwinCode/ellar
repo_name: eadwinCode/ellar
repo_url: https://github.com/eadwinCode/ellar
edit_uri: ''

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  language: en
  logo: img/Icon.svg
  favicon: img/Icon.svg
  icon:
    repo: fontawesome/brands/git-alt

plugins:
- search

nav:
  - Introduction: index.md
  - Quick Overview:
      - Step One:  overview/index.md
      - Controllers:  overview/controllers.md
      - Providers:  overview/providers.md
      - Modules:  overview/modules.md
      - Middlewares:  overview/middleware.md
      - Exception Filters:  overview/exception-filters.md
      - Guards:  overview/guards.md
      - Custom Decorators:  overview/custom-decorators.md
      - How-to Guides:
        - Parsing Request Inputs:
            - Body: overview/how-to-guide/parsing-inputs/body.md
            - Form: overview/how-to-guide/parsing-inputs/form-param.md
            - File: overview/how-to-guide/parsing-inputs/file-param.md
            - Path: overview/how-to-guide/parsing-inputs/path-param.md
            - Query: overview/how-to-guide/parsing-inputs/query-param.md
        - Handling Responses:
          - Response: overview/handling-responses/responses.md
  - Basics:
      - Configuration: basics/configurations.md
      - Execution Context: basics/execution-context.md
      - Custom Providers: basics/custom-providers.md
      - Injection Scopes: basics/injection-scope.md
      - Model View Controller: basics/model-view-controller.md
      - Serialization: basics/serialization.md
      - Static Files: basics/staticfiles.md
      - Events: basics/events.md
      - Versioning: basics/versioning.md
      - Commands: basics/commands.md
      - Templating: basics/templating.md
      - Testing: basics/testing.md
  - OpenAPI: openapi/index.md
  - WebSockets: websockets.md
  - Mount: mount.md
  - Templates: templates.md
  - Events: events.md
  - Background Tasks: background-task.md
  - Release Notes: release-notes.md

markdown_extensions:
- codehilite
- admonition
- pymdownx.superfences
extra_css:
  - stylesheets/extra.css
